### ISSUE TITLE
Enforce the CLA check on All Public Repos

### ISSUE THREAD

**Issue by feanil** [openedx/terraform-github#38]
Ensure the `openedx-webhooks` bot has the right permissions to be able to write status on PRs for all public repos.

**Comment by nedbat** [comment]
This is done now, correct?

**Comment by feanil** [comment]
Yes we ran the script that was merged in with this PR: https://github.com/openedx/terraform-github/pull/39  We have a ticket for automating it to run regularly in the future.  https://github.com/openedx/terraform-github/issues/40
