### ISSUE TITLE
Need Label Created for funded project FC-0006 "Credentials Integration"

### ISSUE THREAD

**Issue by mphilbrick211** [openedx/terraform-github#50]
Need a label created to apply to pull requests related to funded project FC-0006 "Credentials Integration."

Label should read "FC-0006 Credentials Integration" (if that is too long, ok to shorten to FC-0006 Credentials). Turquoise color if possible.

**Comment by mphilbrick211** [comment]
Closing this as @e0d has already created one.

**Comment by sarina** [comment]
@e0d this label should be added to this repo so that it is persisted across all repos and synced to new ones. What did you do?

**Comment by sarina** [comment]
Also I'd recommend removing the 000 if possible (would it be ok to do FC-6?) it's going to be hard to differentiate "FC-0006" and "FC-0007" and etc, but FT-6 and FC-7 are easy to distinguish

**Comment by feanil** [comment]
It sounds like maybe this label was only needed in certain repos and not everywhere?  So it was created in the relevant repos?  I'm gonna close for now but feel free to re-open if we feel we need this in all the repos in which case it should live here.
