### ISSUE TITLE
Add functionality to pass a description in to label sync

### ISSUE THREAD

**Issue by sarina** [openedx/terraform-github#52]
Labels can have an optional description, which you can pass into the API call to labels. It is useful to have this!

<img width="592" alt="image" src="https://user-images.githubusercontent.com/1985317/217267469-b355a150-e41f-4f25-9ef4-85cab0131f52.png">

In the "add labels" code, add functionality to pass not just label name & color, but also description.

**Comment by kdmccormick** [comment]
Will be implemented in https://github.com/openedx/terraform-github/pull/60

**Comment by kdmccormick** [comment]
Implemented by https://github.com/openedx/terraform-github/pull/60
